### ISSUE TITLE
Opens new tab on OmniPreviousHistory

### ISSUE THREAD

**Issue by Bellavene** [Neko-Box-Coder/MicroOmni#4]
Strangely it opens a new tab for each press of OmniPreviousHistory.

Btw, nice additions, very useful.

**Comment by Neko-Box-Coder** [comment]
@Bellavene 
If your previous cursor history is from a file that is not currently open, 
(i.e. You opened a file in a new tab and then closed it)
it will open that file in a new tab.

If you already have that file opened, it will switch to that tab. Unless it is not working properly.

Is it opening a new tab even when you have that file opened already?

If you don't want it to open files that are not opened, I can add an option for that quite easily

**Comment by Bellavene** [comment]
1. nope
2. it just opens the same document in a new tab with the previous location

**Comment by Neko-Box-Coder** [comment]
I have just created a release with the fix. Please do `micro -plugin update MicroOmni` and see if the latest version fixes it.

If not, could you please provide the steps to trigger the bug

**Comment by Bellavene** [comment]
Thank You. Fixed
